### ISSUE TITLE
Tests in error due to missing webapps/proxy directory

### ISSUE THREAD

**Issue by yussufsh** [OpenPOWER-BigData/HDP-Hadoop#1]
**Failed project:** hadoop-yarn-server-web-proxy
**Tests in error:**
  TestWebAppProxyServer.testStart:54 ? ServiceState java.io.FileNotFoundExceptio...
  TestWebAppProxyServlet.testAppReportForEmptyTrackingUrl:210 ? ServiceState jav...
  TestWebAppProxyServlet.testWebAppProxyServerMainMethod:270 ? ServiceState java...
  TestWebAppProxyServlet.testWebAppProxyServlet:128 ? ServiceState java.io.FileN...

**Stacktrace:**
org.apache.hadoop.service.ServiceStateException: java.io.FileNotFoundException: webapps/proxy not found in CLASSPATH
        at org.apache.hadoop.http.HttpServer2.getWebAppsPath(HttpServer2.java:788)
        at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:334)
        at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:114)
        at org.apache.hadoop.http.HttpServer2$Builder.build(HttpServer2.java:290)
        at org.apache.hadoop.yarn.server.webproxy.TestWebAppProxyServlet$WebAppProxyForTest.serviceStart(TestWebAppProxyServlet.java:367)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
        at org.apache.hadoop.service.CompositeService.serviceStart(CompositeService.java:120)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
        at org.apache.hadoop.yarn.server.webproxy.TestWebAppProxyServlet.testWebAppProxyServlet(TestWebAppProxyServlet.java:128)

**Comment by yussufsh** [comment]
Found that error is due to missing directory in /root/yussuf/HDP-Hadoop/hadoop-yarn-project/hadoop-yarn/src/main/resources/webapps/

**Comment by yussufsh** [comment]
hadoop-yarn-applications-distributedshell and hadoop-yarn-applications-unmanaged-am-launcher project failures are also related to this issue.

org.apache.hadoop.yarn.exceptions.YarnRuntimeException: java.io.IOException: ApplicationHistoryServer failed to start. Final state is STOPPED

From surefire report found exception log mentioning the Http server was unable to start because of no file webapps/cluster.

Seems that the initial drop from HW was not proper, probably because of hidden files inside these directories.
**Differrence between OpenPower HDP-Hadoop repo and Hortonworks repo:**
[root@a554138ee798 ws]# diff HDP-Hadoop/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/webapps/ hadoop-release/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/webapps/
Only in hadoop-release/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/webapps/: applicationhistory
Only in hadoop-release/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/webapps/: cluster
Only in hadoop-release/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/webapps/: jobhistory
Only in hadoop-release/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/webapps/: mapreduce
Only in hadoop-release/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/webapps/: node
Only in hadoop-release/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/webapps/: proxy
Common subdirectories: HDP-Hadoop/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/webapps/static and hadoop-release/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/webapps/static
Only in hadoop-release/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/webapps/: test
Only in hadoop-release/hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/resources/webapps/: yarn

**Comment by asanjar** [comment]
thanks for the issue, uploaded the missing files

**Comment by yussufsh** [comment]
Thank you for the commit.
